{% set name = "nordugrid-arc" %}
{% set version = "6.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://source.coderefinery.org/nordugrid/arc/-/archive/v{{ version }}/arc-v{{ version }}.tar.gz
  sha256: 9255a83935b3456646a9bc387f7c6f8d5c75950d39fa3b7558d950fd13f8c5ad

build:
  number: 1
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - make
    - autoconf
    - automake
    - libtool
  host:
    - python
    - swig
    - cppunit
    - gct
    - gfal2
    - glib
    - glibmm
    - libsigcpp =2
    - libuuid
    - libxml2
    - openssl
    - sqlite
    - xrootd
    - zlib
  run:
    - python
    - {{ pin_compatible('glibmm') }}

test:
  commands:
    - arccat --help
    - arccat --help
    - arcclean --help
    - arccp --help
    - arcget --help
    - arcinfo --help
    - arckill --help
    - arcls --help
    - arcmkdir --help
    - arcplugin --help
    - arcproxy --help
    - arcrename --help
    - arcrenew --help
    - arcresub --help
    - arcresume --help
    - arcrm --help
    - arcstat --help
    - arcsub --help
    - arcsync --help
    - arctest --help
  imports:
    # This doesn't actually test anything as it's wrapped in a try catch...
    - arc
    - _arc
    - arc.common
    - arc.loader
    - arc.message
    - arc.compute
    - arc.communication
    - arc.credential
    - arc.data
    - arc.delegation
    - arc.security

about:
  home: http://www.nordugrid.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Advanced Resource Connector Middleware'
  description: |
    The Advanced Resource Connector (ARC) middleware, developed by the
    [NorduGrid Collaboration](http://www.nordugrid.org>), is an open source software
    solution enabling e-Science computing infrastructures with emphasis on
    processing of large data volumes.
    ARC has been used to enable national and international e-infrastructures
    since its first release in 2002.
  doc_url: http://www.nordugrid.org/arc/arc6
  dev_url: https://source.coderefinery.org/nordugrid/

extra:
  recipe-maintainers:
    - chrisburr
